"""add archive flags

Revision ID: 035608a3fbff
Revises: ba4d53daf701
Create Date: 2026-01-20 21:35:51.101695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035608a3fbff'
down_revision = 'ba4d53daf701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
