"""Add archived_at to Dog

Revision ID: 133139d3af9b
Revises: 035608a3fbff
Create Date: 2026-01-20 21:54:44.957708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133139d3af9b'
down_revision = '035608a3fbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
