"""Add address fields to user

Revision ID: 1448c387c730
Revises: 415fab7ae876
Create Date: 2026-01-13 19:32:08.313356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1448c387c730'
down_revision = '415fab7ae876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('province')
        batch_op.drop_column('municipality')
        batch_op.drop_column('barangay')

    # ### end Alembic commands ###
