"""Add email_verified to User

Revision ID: 1cef6ddff700
Revises: fcc3bfc176d8
Create Date: 2026-01-04 21:09:33.306434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cef6ddff700'
down_revision = 'fcc3bfc176d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('phone_otp')
        batch_op.drop_column('phone_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
