"""Added vaccination location fields to Dog

Revision ID: 20bb0bba9a03
Revises: 9f38d187f0de
Create Date: 2026-02-19 00:30:27.798858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bb0bba9a03'
down_revision = '9f38d187f0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccination_barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vaccination_municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vaccination_province', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('vaccination_province')
        batch_op.drop_column('vaccination_municipality')
        batch_op.drop_column('vaccination_barangay')

    # ### end Alembic commands ###
