"""Fix notification relationships

Revision ID: 21b3f3526dd7
Revises: 1cef6ddff700
Create Date: 2026-01-06 15:50:28.727054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b3f3526dd7'
down_revision = '1cef6ddff700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.alter_column('vaccinated',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Not Vaccinated'::character varying"))
        batch_op.drop_constraint(batch_op.f('dog_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('qr_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dog_owner_id_fkey'), 'user', ['owner_id'], ['id'])
        batch_op.alter_column('vaccinated',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Not Vaccinated'::character varying"))

    # ### end Alembic commands ###
