"""Add vaccination_expiry column

Revision ID: 2817e329ac14
Revises: 7c387d742b78
Create Date: 2026-01-14 23:29:57.371771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2817e329ac14'
down_revision = '7c387d742b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccination_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('vaccination_expiry')

    # ### end Alembic commands ###
