"""Add created_at to User

Revision ID: 415fab7ae876
Revises: 
Create Date: 2026-01-11 17:22:39.507732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415fab7ae876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
