"""new models

Revision ID: 4a5617fe771a
Revises: 8a9581e51ddf
Create Date: 2026-03-08 23:15:14.843189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5617fe771a'
down_revision = '8a9581e51ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dog_registration_deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('dog_registration_deadline')

    # ### end Alembic commands ###
