"""try1

Revision ID: 5a7fbef3593d
Revises: 695be35712e5
Create Date: 2026-03-11 02:57:41.996942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7fbef3593d'
down_revision = '695be35712e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_archive_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('admin_archive_cause', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_deadline', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('admin_archive_cause')
        batch_op.drop_column('admin_archive_reason')

    # ### end Alembic commands ###
