"""new model2

Revision ID: 5cb47d90e112
Revises: 5a7fbef3593d
Create Date: 2026-03-13 21:31:40.995678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb47d90e112'
down_revision = '5a7fbef3593d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_barangay', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('owner_municipality', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('owner_province', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('owner_province')
        batch_op.drop_column('owner_municipality')
        batch_op.drop_column('owner_barangay')

    # ### end Alembic commands ###
