"""new model2

Revision ID: 695be35712e5
Revises: 4a5617fe771a
Create Date: 2026-03-08 23:35:38.979787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695be35712e5'
down_revision = '4a5617fe771a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('dog_registration_deadline')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_deadline')

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dog_registration_deadline', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
