"""added vaccination model

Revision ID: 69f4f3478e9b
Revises: 72b20c3c90ca
Create Date: 2026-01-14 18:35:00.512440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f4f3478e9b'
down_revision = '72b20c3c90ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_type', sa.String(length=100), nullable=True),
    sa.Column('last_vaccination', sa.Date(), nullable=False),
    sa.Column('next_vaccination', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('next_vaccination')
        batch_op.drop_column('last_vaccination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vaccination', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('next_vaccination', sa.DATE(), autoincrement=False, nullable=True))

    op.drop_table('vaccination')
    # ### end Alembic commands ###
