"""try1

Revision ID: 718a881ef8c7
Revises: 5cb47d90e112
Create Date: 2026-03-15 16:25:28.923266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718a881ef8c7'
down_revision = '5cb47d90e112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('owner_mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('owner_mobile')
        batch_op.drop_column('owner_email')

    # ### end Alembic commands ###
