"""milestone

Revision ID: 8a42e8fea8d8
Revises: ab96b24ae6ab
Create Date: 2026-01-16 19:00:27.236668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a42e8fea8d8'
down_revision = 'ab96b24ae6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('milestone')

    # ### end Alembic commands ###
