"""back to basic

Revision ID: 8ab7537bcc35
Revises: 69f4f3478e9b
Create Date: 2026-01-14 21:15:33.537236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ab7537bcc35'
down_revision = '69f4f3478e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination')
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_vaccination', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_vaccination', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('next_vaccination')
        batch_op.drop_column('last_vaccination')

    op.create_table('vaccination',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vaccine_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_vaccination', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('next_vaccination', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], name=op.f('vaccination_dog_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vaccination_pkey'))
    )
    # ### end Alembic commands ###
