"""Add dog archive fields

Revision ID: a2d45aabe1e3
Revises: 8a42e8fea8d8
Create Date: 2026-01-20 21:09:05.161989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d45aabe1e3'
down_revision = '8a42e8fea8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
