"""add last_notification_run to user

Revision ID: ab96b24ae6ab
Revises: b9f9013798b7
Create Date: 2026-01-16 18:26:02.634056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab96b24ae6ab'
down_revision = 'b9f9013798b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notification_run', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_notification_run')

    # ### end Alembic commands ###
