"""fix

Revision ID: b4f406afc422
Revises: 
Create Date: 2026-01-15 01:41:54.313403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f406afc422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vaccination_expiry', sa.Date(), nullable=True))
        batch_op.drop_column('age')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('province')
        batch_op.drop_column('municipality')
        batch_op.drop_column('barangay')

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('vaccination_expiry')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
