"""add unique constraint to notification

Revision ID: b9f9013798b7
Revises: baeefada5322
Create Date: 2026-01-16 18:00:24.319854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f9013798b7'
down_revision = 'baeefada5322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_notification_per_dog', ['user_id', 'dog_id', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('unique_notification_per_dog', type_='unique')

    # ### end Alembic commands ###
