"""Fix ambiguous dog user relationships

Revision ID: ba4d53daf701
Revises: a2d45aabe1e3
Create Date: 2026-01-20 21:15:48.327892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d53daf701'
down_revision = 'a2d45aabe1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted_cause', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['deleted_by_owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by_owner_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted_cause')
        batch_op.drop_column('deleted_reason')

    # ### end Alembic commands ###
