"""Add dismissed flag to notifications

Revision ID: ba54d6ed5b89
Revises: 843780144863
Create Date: 2025-12-29 19:34:29.404132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba54d6ed5b89'
down_revision = '843780144863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dismissed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('dismissed')

    # ### end Alembic commands ###
