"""add sms_sent

Revision ID: cf037a1c16c4
Revises: 
Create Date: 2025-12-23 19:16:21.051537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf037a1c16c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_sent', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('dog_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dog_owner_id_fkey'), 'user', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('sms_sent')

    # ### end Alembic commands ###
