"""Add reset_token fields

Revision ID: d3819a39e5b5
Revises: db616151869c
Create Date: 2026-01-07 00:00:50.690940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3819a39e5b5'
down_revision = 'db616151869c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
