"""Add vaccination_location to Dog

Revision ID: eea49e5708a5
Revises: 20bb0bba9a03
Create Date: 2026-02-19 01:06:19.945387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea49e5708a5'
down_revision = '20bb0bba9a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vaccination_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('vaccination_location')

    # ### end Alembic commands ###
