"""Allow null password for Google users

Revision ID: f24e2e552dd6
Revises: cf037a1c16c4
Create Date: 2025-12-26 21:58:45.824613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24e2e552dd6'
down_revision = 'cf037a1c16c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('sms_sent')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
