"""add age

Revision ID: f3bb2ca92c67
Revises: 8ab7537bcc35
Create Date: 2026-01-14 21:20:26.225618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bb2ca92c67'
down_revision = '8ab7537bcc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###
