"""fix dog model

Revision ID: f965206b10a7
Revises: 21b3f3526dd7
Create Date: 2026-01-06 16:14:57.267223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f965206b10a7'
down_revision = '21b3f3526dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('qr_code', sa.String(length=200), nullable=True))
        batch_op.alter_column('vaccinated',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Not Vaccinated'::character varying"))
        batch_op.drop_constraint(batch_op.f('dog_owner_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dog_owner_id_fkey'), 'user', ['owner_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('vaccinated',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Not Vaccinated'::character varying"))
        batch_op.drop_column('qr_code')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
