"""initial migration

Revision ID: 3ec708ba5f0e
Revises: 
Create Date: 2025-11-16 19:29:48.335009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec708ba5f0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.alter_column('vaccinated',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.alter_column('vaccinated',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
